language: python
python:
  - 3.8
  - 3.9
  - 3.10
env:
  - DJANGO=3.2
  - DJANGO=4.2
  - DJANGO=5.0
before_install:
  - export DJANGO_SETTINGS_MODULE=suit.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install .
script:
  - python manage.py test suit
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.8
      env: DJANGO=5.0
    - python: 3.9
      env: DJANGO=5.0
