name: Test Suite

# Controls when the action will run.
on:
  # Triggers the workflow on push for the master branch.
  push:
    branches: [ master ]
  # Triggers the workflow on pull request for any branch.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10"]
        django-version: [ "3.2" , "4.0", "4.1", "4.2"]
        include:
          - python-version: "3.10"
            django-version: "5.0"
    steps:
      # Checks-out the  repository.
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            dev_requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
          pip install -q Django==${{ matrix.django-version }}.*

      - name: Install Package
        run: pip install -e .

      - name: Run tests
        run: python manage.py test suit
        working-directory: ./test_project
